# Example PersistentVolume for NFS CSI driver
# This example shows how to create a PV that mounts an NFS share

# ReadWriteMany example
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-rwx
  labels:
    app: nfs-example
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-csi
  csi:
    driver: nfs.csi.takutakahashi.dev
    # volumeHandle must be unique for each PV
    volumeHandle: nfs-pv-rwx-unique-id
    volumeAttributes:
      server: "192.168.1.100"
      share: "/exports/data"
  mountOptions:
    - nfsvers=4.1
    - hard
---
# ReadOnlyMany example
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-rox
  labels:
    app: nfs-example
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-csi
  csi:
    driver: nfs.csi.takutakahashi.dev
    volumeHandle: nfs-pv-rox-unique-id
    readOnly: true
    volumeAttributes:
      server: "192.168.1.100"
      share: "/exports/readonly-data"
  mountOptions:
    - nfsvers=4.1
    - hard
    - ro
---
# Example with subPath - mounts a subdirectory of the NFS share
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-subpath
  labels:
    app: nfs-example-subpath
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-csi
  csi:
    driver: nfs.csi.takutakahashi.dev
    volumeHandle: nfs-pv-subpath-unique-id
    volumeAttributes:
      server: "192.168.1.100"
      share: "/exports/data"
      # subPath specifies a subdirectory within the NFS share to mount
      # The actual mount path will be: server:/exports/data/tenant1/app1
      subPath: "tenant1/app1"
  mountOptions:
    - nfsvers=4.1
    - hard
